"""Load the Home Credit CSVs into Postgres.

Two responsibilities, deliberately separated:

  emit_schema()  Development-time. Reads each CSV in full to infer column types,
                 then writes sql/schema.sql. Run once, commit the result.
  load()         Runtime. Applies the committed schema.sql, COPYs the CSVs in,
                 builds indexes, and provisions the read-only chatbot role.

The split matters because type inference needs a full pass over 740MB, and the
evaluator should never pay that cost. They run load(), which reads a committed
DDL file.

load() is idempotent. It skips any table that already holds rows unless
FORCE_RELOAD is set, so a second `docker-compose up` starts in seconds.
"""

from __future__ import annotations

import argparse
import warnings
from pathlib import Path

import pandas as pd
import psycopg2
from psycopg2 import sql

from src.utils.config import ALLOWED_TABLES, get_settings
from src.utils.docker_utils import data_file, project_root
from src.utils.helpers import human_count, timed, to_identifier
from src.utils.logger import get_logger

log = get_logger(__name__)

# Table name to source CSV. Keys must match ALLOWED_TABLES exactly: the loader
# creates these tables and the SQL validator whitelists the same names.
TABLE_FILES: dict[str, str] = {
    "application_train": "application_train.csv",
    "bureau": "bureau.csv",
    "previous_application": "previous_application.csv",
}

# Every table carries this column, and every join in the chatbot goes through
# it. Without the index, bureau and previous_application joins are unusable.
JOIN_KEY = "sk_id_curr"

# Type widening order. A column takes the widest type observed across all
# chunks, so a column that looks integral in the first 100k rows but turns
# fractional later still gets a type that can hold it.
_RANK = {"BIGINT": 0, "DOUBLE PRECISION": 1, "TEXT": 2}

_CHUNK_ROWS = 200_000


# --------------------------------------------------------------------------
# Schema generation (development time)
# --------------------------------------------------------------------------

def _pandas_to_pg(dtype: object) -> str:
    kind = getattr(dtype, "kind", None)
    if kind in ("i", "u"):
        return "BIGINT"
    if kind == "f":
        return "DOUBLE PRECISION"
    return "TEXT"


def infer_column_types(csv_path: Path) -> dict[str, str]:
    """Infer Postgres types by reading the whole CSV in chunks.

    Sampling the first N rows is cheaper but wrong: several Home Credit columns
    are integral early and fractional later, and a BIGINT column would then
    fail the COPY halfway through a 400MB file.
    """
    types: dict[str, str] = {}
    reader = pd.read_csv(csv_path, chunksize=_CHUNK_ROWS, low_memory=False)
    for chunk in reader:
        for raw_name, dtype in chunk.dtypes.items():
            column = to_identifier(str(raw_name))
            candidate = _pandas_to_pg(dtype)
            current = types.get(column)
            if current is None or _RANK[candidate] > _RANK[current]:
                types[column] = candidate
    return types


def emit_schema(output: Path | None = None) -> Path:
    """Write sql/schema.sql from the CSVs. Run once, then commit the file."""
    output = output or project_root() / "sql" / "schema.sql"
    output.parent.mkdir(parents=True, exist_ok=True)

    blocks: list[str] = [
        "-- Generated by: python -m src.data.loader --emit-schema",
        "-- Column names are lowercased so generated SQL never needs quoting.",
        "",
    ]

    for table, filename in TABLE_FILES.items():
        path = data_file(filename)
        with timed(f"infer types for {table}"):
            types = infer_column_types(path)
        log.info("%s: %d columns", table, len(types))

        columns = ",\n".join(f"    {name} {pgtype}" for name, pgtype in types.items())
        blocks.append(f"CREATE TABLE IF NOT EXISTS {table} (\n{columns}\n);")
        blocks.append("")

    for table in TABLE_FILES:
        blocks.append(
            f"CREATE INDEX IF NOT EXISTS idx_{table}_{JOIN_KEY} "
            f"ON {table} ({JOIN_KEY});"
        )

    output.write_text("\n".join(blocks) + "\n", encoding="utf-8")
    log.info("wrote %s", output)
    return output


# --------------------------------------------------------------------------
# Loading (runtime)
# --------------------------------------------------------------------------

def _table_row_count(cur, table: str) -> int:
    cur.execute(
        sql.SQL("SELECT count(*) FROM {}").format(sql.Identifier(table))
    )
    return int(cur.fetchone()[0])


def _table_exists(cur, table: str) -> bool:
    cur.execute("SELECT to_regclass(%s) IS NOT NULL", (table,))
    return bool(cur.fetchone()[0])


def _csv_columns(csv_path: Path) -> list[str]:
    header = pd.read_csv(csv_path, nrows=0)
    return [to_identifier(str(c)) for c in header.columns]


def apply_schema(conn) -> None:
    schema_path = project_root() / "sql" / "schema.sql"
    if not schema_path.exists():
        raise FileNotFoundError(
            f"{schema_path} is missing. Generate it with "
            f"`python -m src.data.loader --emit-schema`."
        )
    with conn.cursor() as cur:
        cur.execute(schema_path.read_text(encoding="utf-8"))
    conn.commit()
    log.info("schema applied")


def copy_table(conn, table: str, csv_path: Path) -> int:
    """Stream one CSV into Postgres with COPY FROM STDIN.

    Streaming from the client rather than using a server-side COPY means the
    Postgres container never needs to mount the dataset volume.
    """
    columns = _csv_columns(csv_path)
    statement = sql.SQL("COPY {} ({}) FROM STDIN WITH (FORMAT csv, HEADER true)").format(
        sql.Identifier(table),
        sql.SQL(", ").join(sql.Identifier(c) for c in columns),
    )
    with conn.cursor() as cur:
        with csv_path.open("r", encoding="utf-8", newline="") as handle:
            cur.copy_expert(statement.as_string(cur), handle)
        rows = _table_row_count(cur, table)
    conn.commit()
    return rows


def ensure_readonly_role(conn) -> None:
    """Create the chatbot's SELECT-only role.

    Lives in Python rather than a static .sql file because the password comes
    from the environment and must be parameterised, never interpolated.
    """
    settings = get_settings()
    role = settings.postgres_ro_user
    password = settings.postgres_ro_password

    with conn.cursor() as cur:
        cur.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (role,))
        exists = cur.fetchone() is not None

        if exists:
            cur.execute(
                sql.SQL("ALTER ROLE {} WITH LOGIN PASSWORD {}").format(
                    sql.Identifier(role), sql.Literal(password)
                )
            )
        else:
            cur.execute(
                sql.SQL("CREATE ROLE {} WITH LOGIN PASSWORD {}").format(
                    sql.Identifier(role), sql.Literal(password)
                )
            )

        # Grant exactly SELECT on exactly the three whitelisted tables.
        cur.execute(
            sql.SQL("GRANT CONNECT ON DATABASE {} TO {}").format(
                sql.Identifier(settings.postgres_db), sql.Identifier(role)
            )
        )
        cur.execute(
            sql.SQL("GRANT USAGE ON SCHEMA public TO {}").format(sql.Identifier(role))
        )
        for table in ALLOWED_TABLES:
            cur.execute(
                sql.SQL("GRANT SELECT ON {} TO {}").format(
                    sql.Identifier(table), sql.Identifier(role)
                )
            )
        # Anything created later stays out of reach unless granted explicitly.
        cur.execute(
            sql.SQL(
                "ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM {}"
            ).format(sql.Identifier(role))
        )
    conn.commit()
    log.info("read-only role %s ready", role)


def load(force: bool | None = None) -> None:
    settings = get_settings()
    force = settings.force_reload if force is None else force

    with psycopg2.connect(settings.dsn()) as conn:
        apply_schema(conn)

        for table, filename in TABLE_FILES.items():
            with conn.cursor() as cur:
                if not _table_exists(cur, table):
                    raise RuntimeError(f"{table} missing after applying schema.sql")
                existing = _table_row_count(cur, table)

            if existing and not force:
                log.info("%s: %s rows already present, skipping",
                         table, human_count(existing))
                continue

            if existing and force:
                with conn.cursor() as cur:
                    cur.execute(sql.SQL("TRUNCATE {}").format(sql.Identifier(table)))
                conn.commit()
                log.info("%s: truncated for reload", table)

            csv_path = data_file(filename)
            with timed(f"load {table}"):
                rows = copy_table(conn, table, csv_path)
            log.info("%s: %s rows loaded", table, human_count(rows))

        ensure_readonly_role(conn)

    log.info("load complete")


# --------------------------------------------------------------------------
# Reading back out
# --------------------------------------------------------------------------

def _read_sql(query: str, conn, params: dict | None = None) -> pd.DataFrame:
    """pandas.read_sql over a raw psycopg2 connection.

    pandas warns that only SQLAlchemy connectables are tested. SQLAlchemy is
    not worth a dependency here: every read is a plain SELECT and the chatbot's
    query path deliberately uses raw psycopg2 so it can pin a read-only role
    and a statement timeout. The warning is silenced at the one call site
    rather than globally.
    """
    with warnings.catch_warnings():
        warnings.filterwarnings(
            "ignore",
            message="pandas only supports SQLAlchemy connectable",
            category=UserWarning,
        )
        return pd.read_sql(query, conn, params=params)


def read_table(
    table: str,
    columns: list[str] | None = None,
    limit: int | None = None,
) -> pd.DataFrame:
    """Read a whitelisted table into pandas.

    Training reads from Postgres rather than from the CSV so that the model
    sees exactly the same values, types, and column casing as the chatbot and
    the prediction endpoints. One source, one casing convention, no drift.
    """
    if table not in ALLOWED_TABLES:
        raise ValueError(f"{table!r} is not a whitelisted table")

    selection = ", ".join(columns) if columns else "*"
    query = f"SELECT {selection} FROM {table}"
    if limit:
        query += f" LIMIT {int(limit)}"

    settings = get_settings()
    with psycopg2.connect(settings.dsn()) as conn:
        return _read_sql(query, conn)


def read_application_table(limit: int | None = None) -> pd.DataFrame:
    """The model's training frame.

    application_train only. bureau and previous_application are loaded for the
    talk-to-data layer, which needs more than one table to answer a join
    question, but the model does not consume them. Folding prior credit history
    in would mean rebuilding those aggregates for a single applicant at
    inference time, and a divergence between the training aggregate and the
    serving aggregate fails silently.
    """
    return read_table("application_train", limit=limit)


def fetch_applicant(sk_id_curr: int) -> pd.DataFrame:
    """One applicant row, for the prediction and explanation endpoints."""
    settings = get_settings()
    query = "SELECT * FROM application_train WHERE sk_id_curr = %(sk_id)s"
    with psycopg2.connect(settings.dsn()) as conn:
        return _read_sql(query, conn, params={"sk_id": int(sk_id_curr)})


def main() -> None:
    parser = argparse.ArgumentParser(description="Home Credit to Postgres loader")
    parser.add_argument(
        "--emit-schema",
        action="store_true",
        help="regenerate sql/schema.sql from the CSVs (development only)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="truncate and reload tables that already hold rows",
    )
    args = parser.parse_args()

    if args.emit_schema:
        emit_schema()
        return
    load(force=args.force or None)


if __name__ == "__main__":
    main()
